### ISSUE TITLE
Hello there! I'd like to contribute

### ISSUE THREAD

**Issue by l1uk** [serenial/g-augmented-reality-toolkit#1]
I am a CS bachelor student interested in AR & VR development and looking for something to contribute to. I found your project with a quick GH search and I'd like to help you realise it! Even just by doing some research or peeking through the code or writing issues etc..

I am proficient in programming and conventional informatics but kind of new to the world of engines/game development and interested in learning; my attention was drawn to this field after taking an advanced C++ course.

I hope I can help! Let me know if you're interested, or if you have some suggestions to start approaching this.

**Comment by j-medland** [comment]
Hello

Thanks for the kind offer.

I am developing this library as a toolkit/library to work with the LabVIEW Programming Language / eco-system. 

If you haven't come across LabVIEW before, it is a graphical programming envionment where you "draw" your code and has traditionally been used by scientists and engineers for building test and measurement systems. https://en.wikipedia.org/wiki/LabVIEW

The majority of the C++ code in this library will be devoted to wrapping OpenCV functions in a shared-library binary (.dll or .so) which can be called from LabVIEW, so most of the actual tools which enable the AR will be LabVIEW based so this might not align with your interests.

Unfortunately I don't have a good idea of AR projects which might be more suitable for you to look at.

If you are interested in understanding some of the principles behind AR then this document has some of the theory/mathematics relating to homography https://docs.opencv.org/4.x/d9/dab/tutorial_homography.html

And I started with some AR fundamentals with the ArUco library which you could learn more about here:
https://www.youtube.com/playlist?list=PL7EOs-8ZXfMb2qRog9wOa3Ar-EyvRYdrp

It is worth noting that the OpenCV version of the ArUco library does not have as many refinements as the newer versions but it has a more permissive open-source licence - although this shouldn't matter unless you are using it for commercial applications.
https://www.uco.es/investiga/grupos/ava/portfolio/aruco/

Good Luck!

**Comment by l1uk** [comment]
Thanks!
